DROP SEQUENCE INTERESTLISTSEQ;
DROP TABLE INTERESTLIST;

CREATE SEQUENCE INTERESTLISTSEQ;
CREATE TABLE INTERESTLIST(

	INTERESTLIST_NO 	NUMBER 		PRIMARY KEY,
	ID 				VARCHAR2 	NOT NULL,
	RECIPE_NO 		NUMBER 		NOT NULL,
	
	CONSTRAINT FK_INTEREST_ID FOREIGN KEY(ID)
	REFERENCES MEMBER(ID),
	CONSTRAINT FK_INTEREST_RECIPE_NO FOREIGN KEY(RECIPE_NO)
	REFERENCES RECIPE(RECIPE_NO)
);