DROP SEQUENCE MATERIALSEQ;
DROP TABLE MATERIAL;

CREATE SEQUENCE MATERIALSEQ;
CREATE TABLE MATERIAL(

	MATERIAL_NO 		NUMBER,
	RECIPE_NO 			NUMBER,
	MATERIAL_NAME 		VARCHAR2(500) 	NOT NULL,
	MATERIAL_CAPACITY 	VARCHAR2(500) 	NOT NULL,
	MATERIAL_TYPECODE 	NUMBER 			NOT NULL,
	MATERIAL_TYPENAME 	VARCHAR2(200) 	NOT NULL,
	
	CONSTRAINT PK_MATERIAL PRIMARY KEY(MATERIAL_NO, RECIPE_NO),
	CONSTRAINT FK_MATERIAL_RECIPE_NO FOREIGN KEY(RECIPE_NO)
	REFERENCES RECIPE(RECIPE_NO)
);