DROP SEQUENCE MEMBERSEQ;
DROP TABLE MEMBER;

CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MEMBER(

	ID 			VARCHAR2(500) 	PRIMARY KEY,
	PW 			VARCHAR2(500) 	NOT NULL,
	NAME 		VARCHAR2(1000) 	NOT NULL,
	EMAIL 		VARCHAR2(1000) 	NOT NULL,
	PHONE 		VARCHAR2(1000) 	NOT NULL,
	ADDR 		VARCHAR2(2000) 	NOT NULL,
	ENABLED 	VARCHAR2(2) 	NOT NULL,
	BIRTH 		VARCHAR2(1000) 	NOT NULL,
	REGDATE 	DATE 			NOT NULL,
	
	CONSTRAINT CHECK_ENABLED CHECK(ENABLED IN('Y','N'))
);