DROP SEQUENCE PRODUCTLISTSEQ;
DROP TABLE PRODUCTLIST;

CREATE SEQUENCE PRODUCTLISTSEQ;
CREATE TABLE PRODUCTLIST(

	PRODUCTLIST_NO 	NUMBER 			PRIMARY KEY,
	RECIPE_NO 		NUMBER 			NOT NULL,
	RECIPE_NAME 	VARCHAR2(1000) 	NOT NULL,
	RECIPE_IMG 		VARCHAR2(1000) 	NOT NULL,
	SALES_COUNT 	NUMBER 			NOT NULL,
	VIEW_NO 		NUMBER 			NOT NULL,
	
	CONSTRAINT FK_PRODUCTLIST_RECIPE_NO FOREIGN KEY(RECIPE_NO)
	REFERENCES RECIPE(RECIPE_NO)
);
